const cards = [
  { no: 1, jp: "日本語", en: "English" },
  { no: 2, jp: "ウチ、＜自分の歳＞歳やねん。", en: "I'm <your age>." },
  { no: 3, jp: "日本人やで。大阪から来てん。", en: "I'm Japanese. I'm from Osaka." },
  { no: 4, jp: "ウチ、学生やねん。", en: "I'm a student." },
  { no: 5, jp: "オトンは医者で、オカンは記者しとんねん。", en: "My father is a doctor and my mother is a journalist." },
  { no: 6, jp: "好きな色は青や。", en: "My favourite colour is blue." },
  { no: 7, jp: "好きなスポーツはサッカーと水泳やな。", en: "My favourite sports are football and swimming." },
  { no: 8, jp: "アートにめっちゃ興味あんねん。", en: "I'm interested in art." },
  { no: 9, jp: "政治にはこれっぽっちも興味ないわ。", en: "I'm not interested in politics." },
  { no: 10, jp: "寒いねん。窓閉めてくれへん？", en: "I'm cold. Can you close the window, please?" },
  { no: 11, jp: "ウチ、32歳やけど、妹は29歳やで。", en: "I'm 32 years old. My sister is 29." },
  { no: 12, jp: "スティーブ、風邪で寝込んどるわ。", en: "Steve is ill. He's in bed." },
  { no: 13, jp: "ウチの兄貴、めっちゃ犬怖がりよんねん。", en: "My brother is scared of dogs." },
  { no: 14, jp: "今10時やで。あんた、また遅刻やんか！", en: "It's ten o'clock. You're late again." },
  { no: 15, jp: "アンとウチ、めっちゃ仲ええねん。", en: "Ann and I are good friends." },
  { no: 16, jp: "鍵ならテーブルの上にあるで。", en: "Your keys are on the table." },
  { no: 17, jp: "疲れたけど、お腹は空いてへんわ。", en: "I'm tired, but I'm not hungry." },
  { no: 18, jp: "リサ、政治に興味ないねん。アートが好きなんや。", en: "Lisa isn't interested in politics. She's interested in art." },
  { no: 19, jp: "ジェームス、先生ちゃうで。学生や。", en: "James isn't a teacher. He's a student." },
  { no: 20, jp: "あの人らイギリス人ちゃうで。オーストラリア人や。", en: "Those people aren't English. They're Australian." },
  { no: 21, jp: "今日、天気ええけど暑うはないな。", en: "It's sunny today, but it isn't warm." },
  { no: 22, jp: "ほら！クリスおるやん！", en: "Look! There's Chris." },
  { no: 23, jp: "はい、あんたの鍵。", en: "Here's your key." },
  { no: 24, jp: "ウチ、遅刻した？", en: "Am I late?" },
  { no: 25, jp: "オカン、家におる？", en: "Is your mother at home?" },
  { no: 26, jp: "親御さんはお出かけ中？", en: "Are your parents at home?" },
  { no: 27, jp: "部屋の中、寒ないか？", en: "Is it cold in your room?" },
  { no: 28, jp: "その靴ええやん！新品か？", en: "Your shoes are nice. Are they new?" },
  { no: 29, jp: "カメラどこやったっけ？", en: "Where's the camera?" },
  { no: 30, jp: "あんたの車、青色か？", en: "Is your car blue?" },
  { no: 31, jp: "ケイトはロンドン出身なん？", en: "Is Kate from London?" },
  { no: 32, jp: "お腹空いたんか？", en: "Are you hungry?" },
  { no: 33, jp: "ジョージ、元気にしとる？", en: "How is George?" },
  { no: 34, jp: "あの女の人、誰や？", en: "Who's that woman?" },
  { no: 35, jp: "カバン、何色なん？", en: "What colour is your bag?" },
  { no: 36, jp: "今、飯食うとんねん。", en: "I'm eating." },
  { no: 37, jp: "雨降っとるわ。", en: "It's raining." },
  { no: 38, jp: "ほら、あの子ら走っとるで！", en: "They're running." },
  { no: 39, jp: "今、仕事中やねん。テレビ見てへんで。", en: "I'm working. I'm not watching TV." },
  { no: 40, jp: "マリア、新聞読んどるわ。", en: "Maria is reading a newspaper." },
  { no: 41, jp: "彼女、何も食べとらへんで。", en: "She isn't eating." },
  { no: 42, jp: "バス来たで！", en: "The bus is coming." },
  { no: 43, jp: "ウチら、晩飯食うてんねん。", en: "We're having dinner." },
  { no: 44, jp: "あんた、ウチの話聞いとらんやろ。", en: "You're not listening to me." },
  { no: 45, jp: "子供ら、宿題しとるわ。", en: "The children are doing their homework." },
  { no: 46, jp: "静かにして。今、仕事中やねん。", en: "Please be quiet. I'm working." },
  { no: 47, jp: "テレビ消してええよ。見てへんから。", en: "You can turn off the television. I'm not watching it." },
  { no: 48, jp: "今、何しとんねん？", en: "What are you doing?" },
  { no: 49, jp: "雨、降っとるか？", en: "Is it raining?" },
  { no: 50, jp: "なんでコート着とんの？寒ないやんか。", en: "Why are you wearing a coat? It's not cold." },
  { no: 51, jp: "あの人ら、めっちゃ本読むねん。", en: "They read a lot." },
  { no: 52, jp: "あの子、アイス大好きやねん。", en: "He likes ice cream." },
  { no: 53, jp: "ウチ、店で働いとんねん。", en: "I work in a shop." },
  { no: 54, jp: "兄貴は銀行で働いとるわ。", en: "My brother works in a bank." },
  { no: 55, jp: "ルーシー、ロンドンに住んどるねん。", en: "Lucy lives in London." },
  { no: 56, jp: "親はスコットランド住まいや。", en: "Her parents live in Scotland." },
  { no: 57, jp: "冬はめっちゃ雨降るなあ。", en: "It rains a lot in winter." },
  { no: 58, jp: "ジョー、毎日シャワー浴びよんねん。", en: "Joe has a shower every day." },
  { no: 59, jp: "ウチ、都会が好きやねん。", en: "I like big cities." },
  { no: 60, jp: "あんた、英語めっちゃ上手やん。", en: "You speak English very well." },
  { no: 61, jp: "トムはホンマに頑張り屋やな。", en: "Tom works very hard." },
  { no: 62, jp: "地球は太陽の周りを回っとんねん。", en: "The earth goes round the sun." },
  { no: 63, jp: "暇な時は色んなことしとるわ。", en: "We do a lot of different things in our free time." },
  { no: 64, jp: "スーはいつも仕事行くの早いわ。", en: "Sue always gets to work early." },
  { no: 65, jp: "ウチ、朝飯は絶対食べへんねん。", en: "I never eat breakfast." },
  { no: 66, jp: "週末はよく遊びに行くんや。", en: "We often go away at weekends." },
  { no: 67, jp: "マークは日曜に大抵サッカーしとるな。", en: "Mark usually plays football on Sundays." },
  { no: 68, jp: "コーヒーは飲むけど、紅茶は飲まへん。", en: "I drink coffee, but I don't drink tea." },
  { no: 69, jp: "スーは紅茶派や。コーヒーは飲まへんねん。", en: "Sue drinks tea, but she doesn't drink coffee." },
  { no: 70, jp: "あんた、あんまり頑張ってへんなあ。", en: "You don't work very hard." },
  { no: 71, jp: "ウチら、そんなにテレビ見んわ。", en: "We don't watch TV very often." },
  { no: 72, jp: "天気は大抵ええけど、あんまり雨は降らんな。", en: "The weather is usually nice. It doesn't rain very often." },
  { no: 73, jp: "サムとクリス、あんまり知り合いおらへんねん。", en: "Sam and Chris don't know many people." },
  { no: 74, jp: "フレッドのこと嫌いやし、向こうもウチのこと嫌いやねん。", en: "I don't like Fred and Fred doesn't like me." },
  { no: 75, jp: "ウチの車、あんまりガソリン食わへんわ。", en: "My car doesn't use much petrol." },
  { no: 76, jp: "たまに遅刻しよるけど、しょっちゅうちゃうで。", en: "Sometimes he is late, but it doesn't happen very often." },
  { no: 77, jp: "ギター弾けるん？", en: "Do you play the guitar?" },
  { no: 78, jp: "あんたのダチ、英語喋れるんか？", en: "Do your friends speak English?" },
  { no: 79, jp: "クリス、日曜も仕事しとるん？", en: "Does Chris work on Sundays?" },
  { no: 80, jp: "この辺、雨よう降るんか？", en: "Does it rain a lot here?" },
  { no: 81, jp: "あんたの両親、どこ住んどるん？", en: "Where do your parents live?" },
  { no: 82, jp: "どれくらいの頻度で髪洗っとるん？", en: "How often do you wash your hair?" },
  { no: 83, jp: "「仕事何してんの？」「銀行員やねん」", en: "What do you do? \"I work in a bank.\"" },
  { no: 84, jp: "この単語、どないな意味や？", en: "What does this word mean?" },
  { no: 85, jp: "ニューヨークに電話したらいくら掛かるん？", en: "How much does it cost to phone New York?" },
  { no: 86, jp: "朝飯、大抵何食うとんの？", en: "What do you usually have for breakfast?" },
  { no: 87, jp: "ジャックは今テレビ見とる。ギターは弾いとらん。", en: "Jack is watching television. He is not playing the guitar." },
  { no: 88, jp: "ジャック、ギター持っとるし、よう弾くねんで。", en: "Jack has a guitar, and he often plays it." },
  { no: 89, jp: "あいつ今ギター弾いとるか？いや、弾いてへん。", en: "Is he playing the guitar? No, he isn't." },
  { no: 90, jp: "あいつギター弾くんか？おう、弾くで。", en: "Does he play the guitar? Yes, he does." },
  { no: 91, jp: "静かにせえ。今、仕事しとるんや。", en: "Please be quiet. I'm working." },
  { no: 92, jp: "トム、今シャワー浴びとるわ。", en: "Tom is having a shower at the moment." },
  { no: 93, jp: "傘持っていきや。雨降っとるで。", en: "Take an umbrella with you. It's raining." },
  { no: 94, jp: "テレビ消してええで。見てへんし。", en: "You can turn off the television. I'm not watching it." },
  { no: 95, jp: "なんで机の下におんねん？何しとるん？", en: "Why are you under the table? What are you doing?" },
  { no: 96, jp: "毎日9時から5時半まで働いとるわ。", en: "I work every day from 9 o'clock to 5.30." },
  { no: 97, jp: "冬はめっちゃ雨降るなあ。", en: "It rains a lot in winter." },
  { no: 98, jp: "ウチ、あんまりテレビ見んねん。", en: "I don't watch TV very often." },
  { no: 99, jp: "週末は大抵何しとんの？", en: "What do you usually do at weekends?" },
  { no: 100, jp: "ウチ、もう帰りたいわ。", en: "I want to go home now." },
  { no: 101, jp: "ウチ、黒い目しとんねん。", en: "I have black eyes." },
  { no: 102, jp: "トム、妹が二人おるねんで。", en: "Tom has two sisters." },
  { no: 103, jp: "ウチの車、ドアが4つあんねん。", en: "Our car has four doors." },
  { no: 104, jp: "サラ、具合悪そうやな。頭痛いんやって。", en: "Sarah isn't feeling well. She's got a headache." },
  { no: 105, jp: "あの人ら動物好きや。馬1頭、犬3匹、猫6匹も飼っとる。", en: "They have a horse, three dogs, and six cats." },
  { no: 106, jp: "ウチ、車持ってへんねん。", en: "I don't have a car." },
  { no: 107, jp: "あの子ら、子供おらへんねん。", en: "They don't have any children." },
  { no: 108, jp: "ええ家やけど、庭はないねん。", en: "It's a nice house, but it doesn't have a garden." },
  { no: 109, jp: "エイミー、今仕事ないねん。", en: "Amy doesn't have a job at the moment." },
  { no: 110, jp: "カメラ持っとるか？", en: "Do you have a camera?" },
  { no: 111, jp: "ヘレン、車持っとるんか？", en: "Does Helen have a car?" },
  { no: 112, jp: "どんな車持っとるんや？", en: "What kind of car does she have?" },
  { no: 113, jp: "子供何人おるん？", en: "How many children do they have?" },
  { no: 114, jp: "鍵持っとるか？おう、持っとるで。", en: "Have you got your key? Yes, I have." },
  { no: 115, jp: "アニータ、車持っとるん？いや、持ってへん。", en: "Does Anita have a car? No, she doesn't." },
  { no: 116, jp: "今は仕事中や。昨日の夜中は家におったけどな。", en: "Now I am at work. At midnight last night I was at home." },
  { no: 117, jp: "今、リサはどこにおるん？", en: "Where is Lisa now?" },
  { no: 118, jp: "リサ、昨日はどこにおったんや？", en: "Where was Lisa yesterday?" },
  { no: 119, jp: "今日は天気ええなあ。", en: "The weather is good today." },
  { no: 120, jp: "先週は天気よかったな。", en: "The weather was good last week." },
  { no: 121, jp: "ウチ、今疲れとんねん。", en: "I am tired." },
  { no: 122, jp: "昨日の夜は疲れとったわ。", en: "I was tired last night." },
  { no: 123, jp: "あんた、今遅刻やで。", en: "You are late." },
  { no: 124, jp: "あんた、昨日も遅刻やったやん。", en: "You were late yesterday." },
  { no: 125, jp: "あの人ら、今はここにおらへん。", en: "They aren't here." },
  { no: 126, jp: "先週の日曜、あの人らここにおらへんかったわ。", en: "They weren't here last Sunday." },
  { no: 127, jp: "ウチがガキの頃、犬がめっちゃ怖かってん。", en: "When I was a child, I was scared of dogs." },
  { no: 128, jp: "旅の後はお腹空いとったけど、疲れはせんかったわ。", en: "We were hungry after the journey, but we weren't tired." },
  { no: 129, jp: "ホテルは快適やったけど、高くはなかったで。", en: "The hotel was comfortable, but it wasn't expensive." },
  { no: 130, jp: "休暇中の天気はよかったん？", en: "Was the weather nice when you were on holiday?" },
  { no: 131, jp: "その靴ええやん。高かったんか？", en: "Your shoes are nice. Were they expensive?" },
  { no: 132, jp: "なんで今朝、遅刻したんや？", en: "Why were you late this morning?" },
  { no: 133, jp: "「昨日仕事やった？」「おう、そうやで」", en: "Were you at work yesterday? \"Yes, I was.\"" },
  { no: 134, jp: "「スーとスティーブ、パーティーにおった？」「いや、おらんかった」", en: "Were Sue and Steve at the party? \"No, they weren't.\"" },
  { no: 135, jp: "昨日の午後3時、ジョーはベッドで寝とったわ。", en: "Joe was in bed at 3 o'clock yesterday afternoon." },
  { no: 136, jp: "ジャックとケイト、映画館におったで。", en: "Jack and Kate were at the cinema." },
  { no: 137, jp: "スーは駅におったわ。", en: "Sue was at the station." },
  { no: 138, jp: "ホール夫妻は公園におったで。", en: "Mr and Mrs Hall were in the park." },
  { no: 139, jp: "去年、レイチェルは22歳やったから、今は23歳やな。", en: "Last year Rachel was 22, so she is 23 now." },
  { no: 140, jp: "今朝はめっちゃ寒かったけど、今はええ天気やな。", en: "It was very cold this morning, but now it's nice." },
  { no: 141, jp: "お腹空いたんやけど、なんか食うもんある？", en: "I'm hungry. Can I have something to eat?" },
  { no: 142, jp: "今朝は気分ええけど、昨日の夜はホンマに疲れとってん。", en: "I feel fine this morning, but I was very tired last night." },
  { no: 143, jp: "金曜の朝11時、どこにおったんや？", en: "Where were you at 11 o'clock last Friday morning?" },
  { no: 144, jp: "その靴買うなや。めっちゃ高いやんけ。", en: "Don't buy those shoes. They're very expensive." },
  { no: 145, jp: "その新しいジャケットええな。高かったん？", en: "I like your new jacket. Was it expensive?" },
  { no: 146, jp: "去年の今頃、ウチはパリにおってん。", en: "This time last year I was in Paris." },
  { no: 147, jp: "サムとジョーどこや？「知らん。さっきまでここにおったけど」", en: "Where are Sam and Joe? \"I don't know. They were here a few minutes ago.\"" },
  { no: 148, jp: "ホテル、最悪やったわ。部屋は狭いし、綺麗ちゃうかったし。", en: "We weren't happy with the hotel. Our room was very small and it wasn't clean." },
  { no: 149, jp: "昨日、祝日やったから銀行閉まっとったわ。", en: "Yesterday was a public holiday, so the banks were closed." },
  { no: 150, jp: "鍵どこや？さっきまでテーブルの上にあったのに！", en: "Where are my keys? They were on the table, but they're not there now." },
  { no: 151, jp: "あの人ら、毎晩テレビ見とるで。", en: "They watch TV every evening." },
  { no: 152, jp: "昨日の夜もあの人らテレビ見とったわ。", en: "They watched TV yesterday evening." },
  { no: 153, jp: "ウチ、毎朝歯磨くねん。今朝も磨いたで。", en: "I clean my teeth every morning. This morning I cleaned my teeth." },
  { no: 154, jp: "テリー、2005年から2011年まで銀行で働いとってん。", en: "Terry worked in a bank from 2005 to 2011." },
  { no: 155, jp: "昨日は午前中ずっと雨やったわ。昼に止んだけどな。", en: "Yesterday it rained all morning. It stopped at lunchtime." },
  { no: 156, jp: "パーティー楽しかったわ！めっちゃ踊ったし、よう喋った！", en: "We enjoyed the party last night. We danced a lot and talked to a lot of people." },
  { no: 157, jp: "パーティーは夜中の12時に終わってん。", en: "The party finished at midnight." },
  { no: 158, jp: "大抵早起きやけど、今朝は9時に起きてん。", en: "I usually get up early, but this morning I got up at 9 o'clock." },
  { no: 159, jp: "昨日は仕事めっちゃ頑張ってん。", en: "We did a lot of work yesterday." },
  { no: 160, jp: "キャロライン、先週3回も映画行ってんで。", en: "Caroline went to the cinema three times last week." },
  { no: 161, jp: "ジェームスが部屋に入ってきて、コート脱いで、座ったんや。", en: "James came into the room, took off his coat and sat down." },
  { no: 162, jp: "部屋、暑かったから窓開けてん。", en: "It was hot in the room, so I opened the window." },
  { no: 163, jp: "映画めっちゃ長かったわ。7時15分に始まって10時に終わってん。", en: "The film was very long. It started at 7.15 and finished at 10 o'clock." },
  { no: 164, jp: "ウチが子供の頃、医者になりたかってん。", en: "When I was a child, I wanted to be a doctor." },
  { no: 165, jp: "その事故、先週の日曜の午後に起きてん。", en: "The accident happened last Sunday afternoon." },
  { no: 166, jp: "昨日はええ天気やったけど、一昨日は一日中雨やったわ。", en: "The weather was nice yesterday, but the day before yesterday it rained all day." },
  { no: 167, jp: "去年の休暇は最高やった！めっちゃええ場所に泊まってん。", en: "We enjoyed our holiday last year. We stayed at a very nice place." },
  { no: 168, jp: "アンナのじいちゃん、90歳の時に亡くなってん。", en: "Anna's grandfather died when he was 90 years old." },
  { no: 169, jp: "昨日、映画行ってん。", en: "I went to the cinema yesterday." },
  { no: 170, jp: "先週の火曜、リサはロンドンからマドリードへ飛んでん。", en: "Last Tuesday Lisa flew from London to Madrid." },
  { no: 171, jp: "朝6時に起きて、コーヒー飲んでん。", en: "She got up at 6 o'clock in the morning and had a cup of coffee." },
  { no: 172, jp: "ジェームス、いつもは車やけど、昨日は歩いて仕事行ってんで。", en: "James always goes to work by car. Yesterday he walked to work." },
  { no: 173, jp: "レイチェル、よく鍵なくすんやけど、先週もなくしよったわ。", en: "Rachel often loses her keys. She lost them last week." },
  { no: 174, jp: "昨日、リンゴ食べてん。", en: "I ate an apple yesterday." },
  { no: 175, jp: "昨日はテレビ見てへんわ。", en: "I didn't watch TV yesterday." },
  { no: 176, jp: "あいつら、昨日はサッカーしてへんで。", en: "They didn't play football yesterday." },
  { no: 177, jp: "テレビ見たん？", en: "Did you watch TV?" },
  { no: 178, jp: "あいつらサッカーしたんか？", en: "Did they play football?" },
  { no: 179, jp: "ウチ、昨日はテレビ見んかった。", en: "I didn't watch TV yesterday." },
  { no: 180, jp: "彼女、よく遊びに行くん？先週は行ったんか？", en: "Does she often go away? Did she go away last week?" },
  { no: 181, jp: "昨日の午後テニスしたけど、勝てんかった。", en: "I played tennis yesterday afternoon, but I didn't win." },
  { no: 182, jp: "買い物行った？いや、そんな時間なかってん。", en: "Did you do the shopping? No, I didn't have time." },
  { no: 183, jp: "映画行ったけど、全然おもろなかった。", en: "We went to the cinema, but we didn't enjoy the film." },
  { no: 184, jp: "妹から電話あったか？", en: "Did your sister call you?" },
  { no: 185, jp: "事故、どないして起きたんや？", en: "How did the accident happen?" },
  { no: 186, jp: "両親、休暇でどこ行ってたん？", en: "Where did your parents go for their holiday?" },
  { no: 187, jp: "昨日、ジョーに会った？いや、会ってへん。", en: "Did you see Joe yesterday? No, I didn't." },
  { no: 188, jp: "日曜、雨降ったか？おう、降ったで。", en: "Did it rain on Sunday? Yes, it did." },
  { no: 189, jp: "ヘレン、パーティー来た？いや、来んかった。", en: "Did Helen come to the party? No, she didn't." },
  { no: 190, jp: "両親、ええ休暇やったって？おう、そうみたいや。", en: "Did your parents have a good holiday? Yes, they did." },
  { no: 191, jp: "バーバラには会ったけど、ジェーンには会ってへん。", en: "I saw Barbara, but I didn't see Jane." },
  { no: 192, jp: "あいつら、月曜は働いたけど火曜は休んどった。", en: "They worked on Monday, but they didn't work on Tuesday." },
  { no: 193, jp: "郵便局は行ったけど、銀行は行かんかった。", en: "We went to the post office, but we didn't go to the bank." },
  { no: 194, jp: "昨日の夜、テレビ見たん？", en: "Did you watch TV last night?" },
  { no: 195, jp: "パーティー楽しかった？", en: "Did you enjoy the party?" },
  { no: 196, jp: "ええ休暇やったか？", en: "Did you have a good holiday?" },
  { no: 197, jp: "仕事、早く終わったん？", en: "Did you finish work early?" },
  { no: 198, jp: "昨日の夜、よう眠れた？", en: "Did you sleep well last night?" },
  { no: 199, jp: "先月、ニューヨーク行ってん。", en: "We went to New York last month." },
  { no: 200, jp: "どこ泊まったん？友達の家や。", en: "Where did you stay? With some friends." },
  { no: 201, jp: "昨日の午後3時半、あいつ泳ぎ始めてん。", en: "At 3.30 he started swimming." },
  { no: 202, jp: "ケリー、本読んどる最中に寝落ちしよったわ。", en: "Kelly fell asleep while she was reading." },
  { no: 203, jp: "あんた、英語喋れるんか？「ちょっとだけな」", en: "Do you speak English? \"Yes, a little.\"" },
  { no: 204, jp: "昨日の11時半、何しとったんや？仕事中か？", en: "What were you doing at 11.30 yesterday? Were you working?" },
  { no: 205, jp: "鍵、持っとるか？いや、持ってへん。", en: "Have you got your key? No, I haven't." },
  { no: 206, jp: "4時やろ？あいつ、そん時泳いどったで。", en: "At 4.00 he was swimming." },
  { no: 207, jp: "「あいつ、なんて言うたんや？」「知らん、聞いてへんかった」", en: "What did he say? \"I don't know. I wasn't listening.\"" },
  { no: 208, jp: "去年、ウチはパリにおってん。", en: "This time last year I was in Paris." },
  { no: 209, jp: "外見たら、雪降っとったわ。", en: "When I looked out, it was snowing." },
  { no: 210, jp: "妹、29歳やねん。", en: "My sister is 29." },
  { no: 211, jp: "雨降っとったから、出かけんかったんや。", en: "It was raining, so we didn't go out." },
  { no: 212, jp: "今朝、何時に起きたんや？", en: "What time did you get up this morning?" },
  { no: 213, jp: "2009年はカナダに住んどったわ。", en: "In 2009 we were living in Canada." },
  { no: 214, jp: "お腹空いとるか？", en: "Are you hungry?" },
  { no: 215, jp: "今日はスカートやけど、昨日はズボン履いとったで。", en: "Today she's wearing a skirt, but yesterday she was wearing trousers." },
  { no: 216, jp: "どこにおるんや？「ここやで！」", en: "Where are you? \"I'm here!\"" },
  { no: 217, jp: "太陽が輝いとって、鳥も歌っとったわ。", en: "The sun was shining and the birds were singing." },
  { no: 218, jp: "トム、アイスはあんまり好きちゃうねん。", en: "Tom doesn't like ice cream." },
  { no: 219, jp: "昨日の夜10時半、仕事しとったわ。", en: "I was working at 10.30 last night." },
  { no: 220, jp: "昨日の夜、何食うたんや？", en: "What did you eat last night?" },
  { no: 221, jp: "出かける時、雨降ってへんかったで。", en: "It wasn't raining when we went out." },
  { no: 222, jp: "ウチ、毎日仕事行くんや。", en: "I go to work every day." },
  { no: 223, jp: "3時、何しとったんや？", en: "What were you doing at 3 o'clock?" },
  { no: 224, jp: "ジャックが本読んどる時に、電話鳴ってん。", en: "Jack was reading a book when his phone rang." },
  { no: 225, jp: "昨日の夜、ずっとテレビ見とった。", en: "I was watching TV all day yesterday." },
  { no: 226, jp: "電話鳴った時、ジャックは何しとったん？", en: "What was Jack doing when his phone rang?" },
  { no: 227, jp: "ウチ、頭痛いねん。", en: "I've got a headache." },
  { no: 228, jp: "電話鳴った時、あいつ何したん？電話に出てん。", en: "What did he do when his phone rang? He answered his phone." },
  { no: 229, jp: "昨日は忙しかったわ。", en: "I was busy yesterday." },
  { no: 230, jp: "昨日の午前中、何しとったんや？", en: "What did you do yesterday morning?" },
  { no: 231, jp: "昨日の10時半、何しとったんや？", en: "What were you doing at 10.30?" },
  { no: 232, jp: "ウチ、学生やねん。", en: "I'm a student." },
  { no: 233, jp: "昨日の夜、テレビで試合見たんか？", en: "Did you watch the game on TV last night?" },
  { no: 234, jp: "昨日の夜、どこおったん？", en: "Where were you last night?" },
  { no: 235, jp: "ウチが電話した時、テレビ見とったんか？", en: "Were you watching TV when I phoned you?" },
  { no: 236, jp: "彼は昨日、仕事休みやってん。", en: "He wasn't at work yesterday." },
  { no: 237, jp: "休暇中、一回も雨降らんかったわ。", en: "It didn't rain while we were on holiday." },
  { no: 238, jp: "ウチ、昨日あの店行ってん。", en: "I went to that shop yesterday." },
  { no: 239, jp: "ウチが起きた時、雨は降ってへんかった。", en: "It wasn't raining when I got up." },
  { no: 240, jp: "9時に仕事始めて、4時半に終わってん。", en: "I started work at 9 o'clock and finished at 4.30." },
  { no: 241, jp: "子供ら、公園におるわ。", en: "The children are in the park." },
  { no: 242, jp: "2時半の時は、バリバリ仕事しとったで。", en: "At 2.30 I was working." },
  { no: 243, jp: "あの映画、見んかったわ。", en: "I didn't see that movie." },
  { no: 244, jp: "外出た瞬間、雨降っとったわ。", en: "It was raining when we went out." },
  { no: 245, jp: "ウチが来た時、何しとったん？", en: "What were you doing when I came?" },
  { no: 246, jp: "今朝、ルーシーらに会ったで。バス停で待っとったわ。", en: "I saw Lucy and Steve this morning. They were waiting at the bus stop." },
  { no: 247, jp: "晩飯作っとる時に、指切ってん。", en: "She cut her finger while she was cooking dinner." },
  { no: 248, jp: "今、何しとんねん？", en: "What are you doing now?" },
  { no: 249, jp: "あいつ今何しとる？「飯食うとるで」", en: "What's he doing? \"He's having dinner.\"" },
  { no: 250, jp: "なんで泣いとんねん？", en: "Why are you crying?" },
];
